language: node_js
cache: yarn
node_js:
  -  "9"
install: yarn
script: yarn build
deploy:
  provider: s3
  access_key_id: "AKIAJMEXVK4WDZGIM62Q"
  secret_access_key: "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"
  bucket: "lekong"
  local_dir: build
  skip_cleanup: true
